### ISSUE TITLE
[repo] Sane Defaults

### ISSUE THREAD

**Issue by DT9** [devops-ia/helm-opencti#98]
### Is your feature request related to a problem?

Doesn't work out of the box

### Describe the solution you'd like

eg. Work out of the box similar to the docker-compose.
Make secrets injection easier.

### Describe alternatives you've considered

NONE

**Comment by ialejandro** [comment]
hi @DT9, idk if any moment will do it. I like the default values without set `fullnameOverride` over dependencies (MinIO, Redis...) because this may conflict with another services which the community has in their Kubernetes, so I prefer avoid it.

About `secrets` I did this guide <https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/docs/examples.md> to create it with your favourite tool or integrate with external tools such as AWS Secrets Manager with external-secrets, etc.
